using BIApiServer.Common.DbContexts;
using SqlSugar;
using System.Reflection;
using BIApiServer.Interfaces;
using BIApiServer.Models;
using BIApiServer.Models.Interfaces;
namespace BIApiServer.Services
{
    public class AddTableService : IScopedService
    {
        private static AppDbContext _db;

        public AddTableService(AppDbContext db)
        {
            _db = db;
        }

        public async void AddTable()
        {
            var ass = Assembly.GetAssembly(typeof(EntityBases));

            var types = ass.GetTypes().Where(p => p.GetInterface(nameof(IAutoGenerated)) != null && !p.IsAbstract)
                .ToArray();

            foreach (var tp in types)
            {
                await InitTable(tp);
            }
        }

        public async Task InitTable(Type tp)
        {
            var attr = tp.GetCustomAttribute<SugarTable>();
            if (attr != null)
            {
                _db.Default.CodeFirst.InitTables(tp);
            }
        }
    }
}